<template>
  <div class="homeBackground">
    <div class="container py-5">
      <!-- 标题部分 -->
      <div class="text-center mb-5">
        <h1 class="display-5 mb-3">Got questions?</h1>
        <p class="fs-6 mb-4">
          Our team is here to help you succeed in every interview.
        </p>
      </div>

      <el-collapse v-for="(i, index) of visibleFaqs" :key="index" class="mt-3">
        <el-collapse-item :title="i.question" :name="index">
          <div class="text-left">{{ i.answer }}</div>
        </el-collapse-item>
      </el-collapse>

      <div class="text-center mt-4">
        <el-button @click="toggleShowAll" class="default-btn" type="primary">
          {{ showAll ? "Show Less" : "Show All" }}
        </el-button>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  data() {
    return {
      showAll: false,
      faqList: [
        {
          question: "How do I start practicing interviews?",
          answer:
            "Just sign up or log in with Google, choose a practice module, enable your microphone, and hit 'Start' to begin speaking your answers—no extra setup needed.",
        },
        {
          question: "Is there a trial period?",
          answer:
            "Yes! All registered users get a 7-day free trial, giving you full access to all features without the need for a credit card.",
        },
        {
          question:
            "What's the difference between Pay-per-use and Premium plans?",
          answer:
            "The Pay-per-use plan allows you to pay for individual practice sessions and mock interviews as you go, offering flexibility for occasional users. The Premium plan provides unlimited access to all features, including practice sessions, mock interviews, and a final assessment report after each session.",
        },
        {
          question: "Can I practice unlimited questions?",
          answer:
            "During the free trial, you'll get 6 practice sessions and 1 mock interview to explore the platform. After that, you can either buy individual credits or upgrade to Premium for unlimited access to all features.",
        },
        {
          question: "How does the AI evaluate my answers?",
          answer:
            "After each response, our AI coach evaluates your answer for grammar, clarity, sentence structure, and the strength of your examples. You'll also receive a model answer to guide your improvement and help you perform better in future interviews.",
        },
        {
          question:
            "Can I save or download my audio responses and assessments?",
          answer:
            "Yes, you can download your audio responses on all plans and access your final assessments when available. You can also revisit past sessions and track your progress from the History tab.",
        },
        {
          question: "Does the mock interview simulate a real recruiter?",
          answer:
            "Yes, the mock interview simulates a real interview setting with follow-up questions, timed responses, and role-specific scenarios to help you prepare under realistic conditions.",
        },
        {
          question: "Are the interview questions updated regularly?",
          answer:
            "Our questions are dynamically generated by us based on your responses and practice goals. We don't rely on a fixed question bank, so each session is personalized and keeps evolving with you.",
        },
        {
          question: "Is this suitable for non-native English speakers?",
          answer:
            "Absolutely! Our model is designed to understand a wide range of speaking styles. It's especially helpful for non-native English speakers looking to improve fluency, pronunciation, and overall confidence in interviews.",
        },
        {
          question: "What equipment do I need to use this platform?",
          answer:
            "You'll need a device with a working microphone and speakers, a stable internet connection, and a quiet space to help with clear voice recognition and better focus.",
        },
        {
          question: "How can I get support or give feedback?",
          answer:
            "If you need help or would like to share feedback, feel free to reach out to us at customerservice@jobace.ca. Our team is here to assist you and improve your experience!",
        },
      ],
    };
  },
  computed: {
    visibleFaqs() {
      return this.showAll ? this.faqList : this.faqList.slice(0, 5);
    },
  },
  methods: {
    toggleShowAll() {
      this.showAll = !this.showAll;
    },
  },
};
</script>

<style lang="scss" scoped>
h1 {
  font-size: 56px;
}

.el-collapse {
  border-radius: 0.5rem;
  box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1),
    0 2px 4px -1px rgba(0, 0, 0, 0.06);
  margin-bottom: 1rem;
  overflow: hidden;
}

::v-deep .el-collapse-item__header {
  background-color: var(--bg-light-grey);
  padding: 1rem 1.5rem;
  font-weight: 600;
  cursor: pointer;
  transition: background-color 0.3s ease;
  font-size: 16px;
  color: var(--text-primary);
  @media only screen and (max-width: 991px) {
    font-size: 12px;
  }
  @media only screen and (max-width: 431px) {
    font-size: 12px;
    line-height: 1;
    text-align: left;
  }
}

::v-deep .el-collapse-item__header:hover {
  background-color: var(--bg-dark-grey);
}

::v-deep .el-collapse-item__content {
  text-align: left;
  padding: 1rem 1.5rem;
  border-top: 1px solid var(--border-base);
  font-size: 14px;
}

/* 动画效果 */
::v-deep .el-collapse-item__wrap {
  transition: max-height 0.3s ease-in-out;
  overflow: hidden;
}
</style>
